---
apiVersion: v1
kind: Service
metadata:
  name: podinfo2
  namespace: itops
  labels:
    app: podinfo2
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 9899
    targetPort: 9899
    nodePort: 30899
    protocol: TCP    
  selector:
    app: podinfo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
  namespace: itops
  labels:
    app: podinfo2
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regex:^3.10.*
    flux.weave.works/tag.podinfod: semver:~2.1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: podinfo
    spec:
      initContainers:
      - name: init
        image: alpine:3.10.1
        command:
        - sleep
        - "1"
      containers:
      - name: podinfod
        image: stefanprodan/podinfo:2.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9899
          name: http
          protocol: TCP
        command:
        - ./podinfo
        - --port=9899
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_MESSAGE
          value: "Greetings demo audience!"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9899
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9899
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
